### ISSUE TITLE
Error running manage.py

### ISSUE THREAD

**Issue by Pilakoutas03** [casparluc/VikingDoom#1]
This error comes up when I try manage.py
``Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\conf\__init__.py", line 53, in __getattr__
    self._setup(name)
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\conf\__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'C:\\Users\\alexa\\Downloads\\mongodb-engine-master\\mongodb-engine-master
ocal\Programs\Python\Python36-32\lib\site-packages\django\conf\__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'C:\\Users\\alexa\\Downloads\\mongodb-engine-master\\mongodb-engine-master

**Comment by davinellulinvega** [comment]
Hello,

I would have to know a bit more about your database configuration to give you a complete answer, but my first guess would be that something went wrong when you installed the client library for you database or that the library is not present on your python path.

Here is a method to add modules on your python path on windows: https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7

Also have a look at Django's tutorial for installing and configuring databases:
https://docs.djangoproject.com/en/1.10/intro/install/
https://docs.djangoproject.com/en/1.10/topics/install/#database-installation

I should also point out that Django officially supports PostgreSql, Oracle, Sqlite and Mysql only, thus using MongoDB as a backend might lead to further complication down the line. If you are not bound by any other constraints Mysql would be a better alternative.

Sincerely.

**Comment by Pilakoutas03** [comment]
Neither of these worked but when installing MySQL these errors came up.
Failed building wheel for MySQL-python
and
Command "c:\users\alexa\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\alexa\\AppData\\Local\\Temp\\pip-build-_ljrzdwe\\MySQL-python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\alexa\AppData\Local\Temp\pip-u_4rcjqm-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\alexa\AppData\Local\Temp\pip-build-_ljrzdwe\MySQL-python\

**Comment by davinellulinvega** [comment]
Have you tried installing the `mysqlclient` module instead? Since the rest of the project requires you to use Python3 and the `MySQLDb` driver will not work anyway.
`mysqlclient` can be installed via the package manager as well.

Sincerely.

**Comment by Pilakoutas03** [comment]
I already have that installed

**Comment by davinellulinvega** [comment]
That is great!

This means that the database driver is already installed on your system.
All you need now is to configure a new user on your database server (I would recommend MySQL Workbench to ease of use: https://www.mysql.com/products/workbench/) and fill in the settings in the folder `Vikingdoom/settings.py`.
In my case the configuration block looked something like:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'name_of_database',
        'HOST': 'localhost',
        'PORT': '3306',
        'USER': 'username',
        'PASSWORD': 'password',
        'CHARSET': 'utf-8',
        'CON_MAX_AGE': 500,
        'OPTIONS': {
            'sql_mode': 'STRICT_ALL_TABLES'}
    }
}
```

**Comment by Pilakoutas03** [comment]
I'm sorry but I'm completely new to python and mysql could
